Repository nss-day-cohort-46/rare-api-glad-glaepeth, pull requests merged in 2021-05, with the labels that each got.

#57 Nah create tag
  rare/urls.py
  rareapi/views/__init__.py
  rareapi/views/tag.py
Labels: Tags, documentation

#59 fix: you can edit and delete tags / no admin features
  db.session.sql
  rare/urls.py
  rareapi/migrations/0002_auto_20210518_2028.py
  rareapi/migrations/0003_merge_0002_auto_20210518_2028_0002_auto_20210518_2030.py
  rareapi/views/__init__.py
  rareapi/views/tag.py
Labels: Tags, documentation

#64 fix: added logic for edit & delete tags
  .pylintrc
  rare.session.sql
  rareapi/views/tag.py
Labels: Admin, Tags, documentation

#65 Cj comments
  .gitignore
  db.session.sql
  rareapi/views/comment.py
  rareapi/views/user.py
Labels: documentation

#66 fix: added logic to category.py for admin users to edit or delete
  rareapi/views/category.py
Labels: documentation

#67 fix: added validation, id, and is_staff to register user data
  rareapi/views/auth.py
Labels: documentation

#68 fix: added id to user serializer to find user of posts
  rareapi/views/post.py
Labels: documentation

#72 Dm mypostsorderby
  rareapi/migrations/0001_initial.py
  rareapi/views/post.py
Labels: documentation

#73 Nah subscriptions
  rareapi/views/subscription.py
Labels: documentation

#69 fix: added profile_image_url to RareUser
  rareapi/views/auth.py
Labels: Image, Users, documentation
